export const vehicleData = [
  {
    id: 1,
    title: 'Toyota Camry XLE 2022',
    make: 'Toyota',
    model: 'Camry',
    year: 2022,
    price: 18500,
    mileage: 25000,
    location: 'canada',
    shipmentIncluded: true,
    shipmentNotes: '',
    status: 'available',
    isFeatured: true,
    fuelType: 'Hybrid',
    transmission: 'Automatic',
    color: 'White',
    condition: 'Used',
    category: 'sedan',
    bodyType: 'Sedan',
    drivetrain: 'FWD',
    engineSize: '2.5L',
    doors: 4,
    seats: 5
  },
  {
    id: 2,
    title: 'Honda CR-V EX-L 2021',
    make: 'Honda',
    model: 'CR-V',
    year: 2021,
    price: 22000,
    mileage: 32000,
    location: 'canada',
    shipmentIncluded: false,
    shipmentNotes: 'Contact for shipping quote to Ghana',
    status: 'available',
    isFeatured: true,
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    color: 'Black',
    condition: 'Used',
    category: 'suv',
    bodyType: 'SUV',
    drivetrain: 'AWD',
    engineSize: '1.5L',
    doors: 4,
    seats: 5
  },
  {
    id: 3,
    title: 'Mercedes-Benz C300 2020',
    make: 'Mercedes-Benz',
    model: 'C300',
    year: 2020,
    price: 35000,
    mileage: 45000,
    location: 'ghana',
    status: 'available',
    isFeatured: true,
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    color: 'Silver',
    condition: 'Used',
    category: 'sedan',
    bodyType: 'Sedan',
    drivetrain: 'RWD',
    engineSize: '2.0L',
    doors: 4,
    seats: 5
  },
  {
    id: 4,
    title: 'Toyota RAV4 XLE 2023',
    make: 'Toyota',
    model: 'RAV4',
    year: 2023,
    price: 26500,
    mileage: 15000,
    location: 'canada',
    shipmentIncluded: true,
    status: 'available',
    fuelType: 'Hybrid',
    transmission: 'Automatic',
    color: 'Blue',
    condition: 'Used',
    category: 'suv',
    bodyType: 'SUV',
    drivetrain: 'AWD',
    engineSize: '2.5L',
    doors: 4,
    seats: 5
  },
  {
    id: 5,
    title: 'BMW X5 xDrive40i 2021',
    make: 'BMW',
    model: 'X5',
    year: 2021,
    price: 42000,
    mileage: 38000,
    location: 'ghana',
    status: 'reserved',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    color: 'Black',
    condition: 'Used',
    category: 'hybrid',
    bodyType: 'SUV',
    drivetrain: 'AWD',
    engineSize: '3.0L',
    doors: 4,
    seats: 7
  },
  {
    id: 6,
    title: 'Ford Explorer XLT 2022',
    make: 'Ford',
    model: 'Explorer',
    year: 2022,
    price: 29500,
    mileage: 28000,
    location: 'canada',
    shipmentIncluded: false,
    shipmentNotes: 'Shipping available at additional cost',
    status: 'available',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
     color: 'Black',
    condition: 'Used',
    category: 'pickup', 
    bodyType: 'Truck',
    drivetrain: 'RWD',
    engineSize: '2.3L',
    doors: 4,
    seats: 7
  },
  {
    id: 7,
    title: 'Nissan Rogue SV 2022',
    make: 'Nissan',
    model: 'Rogue',
    year: 2022,
    price: 23500,
    mileage: 22000,
    location: 'canada',
    shipmentIncluded: true,
    status: 'available',
    fuelType: 'Gasoline',
    transmission: 'CVT',
    color: 'Silver',
    condition: 'Used',
    category: 'suv',
    bodyType: 'SUV',
    drivetrain: 'AWD',
    engineSize: '2.5L',
    doors: 4,
    seats: 5
  },
  {
    id: 8,
    title: 'Lexus RX 350 2022',
    make: 'Lexus',
    model: 'RX 350',
    year: 2022,
    price: 48500,
    mileage: 18000,
    location: 'canada',
    shipmentIncluded: true,
    status: 'available',
    isFeatured: true,
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    color: 'Silver',
    condition: 'Used',
    category: 'suv',
    bodyType: 'SUV',
    drivetrain: 'AWD',
    engineSize: '3.5L',
    doors: 4,
    seats: 5
  },
  {
    id: 9,
    title: 'Hyundai Tucson Limited 2023',
    make: 'Hyundai',
    model: 'Tucson',
    year: 2023,
    price: 27500,
    mileage: 12000,
    location: 'canada',
    shipmentIncluded: true,
    status: 'available',
    fuelType: 'Hybrid',
    transmission: 'Automatic',
    color: 'Blue',
    condition: 'Used',
    category: 'suv',
    bodyType: 'SUV',
    drivetrain: 'AWD',
    engineSize: '1.6L',
    doors: 4,
    seats: 5
  },
  {
    id: 10,
    title: 'Mazda CX-5 Grand Touring 2022',
    make: 'Mazda',
    model: 'CX-5',
    year: 2022,
    price: 26500,
    mileage: 24000,
    location: 'canada',
    shipmentIncluded: true,
    status: 'available',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    color: 'Red',
    condition: 'Used',
    category: 'suv',
    bodyType: 'SUV',
    drivetrain: 'AWD',
    engineSize: '2.5L',
    doors: 4,
    seats: 5
  },
  {
    id: 11,
    title: 'Acura MDX SH-AWD 2021',
    make: 'Acura',
    model: 'MDX',
    year: 2021,
    price: 38500,
    mileage: 32000,
    location: 'canada',
    shipmentIncluded: true,
    status: 'available',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    color: 'Black',
    condition: 'Used',
    category: 'suv',
    bodyType: 'SUV',
    drivetrain: 'AWD',
    engineSize: '3.5L',
    doors: 4,
    seats: 7
  },
  {
    id: 12,
    title: 'Toyota Highlander Hybrid 2022',
    make: 'Toyota',
    model: 'Highlander',
    year: 2022,
    price: 41500,
    mileage: 28000,
    location: 'canada',
    shipmentIncluded: true,
    status: 'available',
    fuelType: 'Hybrid',
    transmission: 'CVT',
    color: 'White',
    condition: 'Used',
    category: 'suv',
    bodyType: 'SUV',
    drivetrain: 'AWD',
    engineSize: '2.5L',
    doors: 4,
    seats: 7
  },
  {
    id: 13,
    title: 'Honda Accord Sport 2022',
    make: 'Honda',
    model: 'Accord',
    year: 2022,
    price: 24500,
    mileage: 26000,
    location: 'canada',
    shipmentIncluded: true,
    status: 'available',
    fuelType: 'Hybrid',
    transmission: 'CVT',
    color: 'Silver',
    condition: 'Used',
    category: 'sedan',
    bodyType: 'Sedan',
    drivetrain: 'FWD',
    engineSize: '2.0L',
    doors: 4,
    seats: 5
  },
  {
    id: 14,
    title: 'Nissan Altima SR 2022',
    make: 'Nissan',
    model: 'Altima',
    year: 2022,
    price: 20500,
    mileage: 29000,
    location: 'canada',
    shipmentIncluded: true,
    status: 'available',
    fuelType: 'Gasoline',
    transmission: 'CVT',
    color: 'Gray',
    condition: 'Used',
    category: 'sedan',
    bodyType: 'Sedan',
    drivetrain: 'FWD',
    engineSize: '2.5L',
    doors: 4,
    seats: 5
  },
  {
    id: 15,
    title: 'Mercedes-Benz E350 2021',
    make: 'Mercedes-Benz',
    model: 'E350',
    year: 2021,
    price: 42500,
    mileage: 35000,
    location: 'canada',
    shipmentIncluded: true,
    status: 'available',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    color: 'Black',
    condition: 'Used',
    category: 'luxury',
    bodyType: 'Sedan',
    drivetrain: 'RWD',
    engineSize: '3.0L',
    doors: 4,
    seats: 5
  },
  {
    id: 16,
    title: 'Lexus ES 350 2022',
    make: 'Lexus',
    model: 'ES 350',
    year: 2022,
    price: 39500,
    mileage: 22000,
    location: 'canada',
    shipmentIncluded: true,
    status: 'available',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    color: 'Silver',
    condition: 'Used',
    category: 'luxury',
    bodyType: 'Sedan',
    drivetrain: 'FWD',
    engineSize: '3.5L',
    doors: 4,
    seats: 5
  },
  {
    id: 17,
    title: 'Hyundai Santa Fe Calligraphy 2023',
    make: 'Hyundai',
    model: 'Santa Fe',
    year: 2023,
    price: 33500,
    mileage: 14000,
    location: 'canada',
    shipmentIncluded: true,
    status: 'available',
    fuelType: 'Hybrid',
    transmission: 'Automatic',
    color: 'Green',
    condition: 'Used',
    category: 'suv',
    bodyType: 'SUV',
    drivetrain: 'AWD',
    engineSize: '1.6L',
    doors: 4,
    seats: 5
  },
  {
    id: 18,
    title: 'Mazda3 Premium 2022',
    make: 'Mazda',
    model: 'Mazda3',
    year: 2022,
    price: 19500,
    mileage: 27000,
    location: 'canada',
    shipmentIncluded: true,
    status: 'available',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    color: 'Blue',
    condition: 'Used',
    category: 'sedan',
    bodyType: 'Sedan',
    drivetrain: 'AWD',
    engineSize: '2.5L',
    doors: 4,
    seats: 5
  },
   {
    id: 19,
    title: 'Ford F-150 Lightning 2023',  
    make: 'Ford',
    model: 'F-150 Lightning',
    year: 2023,
    price: 59500,
    mileage: 9000,
    location: 'canada',
    shipmentIncluded: true,
    status: 'available',
    isFeatured: true,
    fuelType: 'Electric',
    transmission: 'Automatic',
    color: 'White',
    condition: 'Used',
    category: 'pickup', 
    bodyType: 'Truck',
    drivetrain: 'AWD',
    engineSize: 'Electric',
    doors: 4,
    seats: 5,
    range: '320 miles',
    
  },
  {
    id: 20,
    title: 'Acura TLX A-Spec 2022',
    make: 'Acura',
    model: 'TLX',
    year: 2022,
    price: 35500,
    mileage: 21000,
    location: 'ghana',
    shipmentIncluded: true,
    status: 'available',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    color: 'Red',
    condition: 'Used',
    category: 'luxury',
    bodyType: 'Sedan',
    drivetrain: 'SH-AWD',
    engineSize: '2.0L',
    doors: 4,
    seats: 5
  }
]

export const featuredVehicles = vehicleData.filter(v => v.isFeatured)