export const vehicleData = [
  {
    id: 1,
    title: 'Toyota Camry XLE 2022',
    make: 'Toyota',
    model: 'Camry',
    year: 2022,
    price: 18500,
    mileage: 25000,
    location: 'canada',
    shipmentIncluded: true,
    shipmentNotes: '',
    status: 'available',
    isFeatured: true,
    fuelType: 'Hybrid',
    transmission: 'Automatic',
    color: 'White',
    condition: 'Used',
  },
  {
    id: 2,
    title: 'Honda CR-V EX-L 2021',
    make: 'Honda',
    model: 'CR-V',
    year: 2021,
    price: 22000,
    mileage: 32000,
    location: 'canada',
    shipmentIncluded: false,
    shipmentNotes: 'Contact for shipping quote to Ghana',
    status: 'available',
    isFeatured: true,
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    color: 'Black',
    condition: 'Used',
  },
  {
    id: 3,
    title: 'Mercedes-Benz C300 2020',
    make: 'Mercedes-Benz',
    model: 'C300',
    year: 2020,
    price: 35000,
    mileage: 45000,
    location: 'ghana',
    status: 'available',
    isFeatured: true,
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    color: 'Silver',
    condition: 'Used',
  },
  {
    id: 4,
    title: 'Toyota RAV4 XLE 2023',
    make: 'Toyota',
    model: 'RAV4',
    year: 2023,
    price: 26500,
    mileage: 15000,
    location: 'canada',
    shipmentIncluded: true,
    status: 'available',
    fuelType: 'Hybrid',
    transmission: 'Automatic',
    color: 'Blue',
    condition: 'Used',
  },
  {
    id: 5,
    title: 'BMW X5 xDrive40i 2021',
    make: 'BMW',
    model: 'X5',
    year: 2021,
    price: 42000,
    mileage: 38000,
    location: 'ghana',
    status: 'reserved',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    color: 'Black',
    condition: 'Used',
  },
  {
    id: 6,
    title: 'Ford Explorer XLT 2022',
    make: 'Ford',
    model: 'Explorer',
    year: 2022,
    price: 29500,
    mileage: 28000,
    location: 'Ghana',
    shipmentIncluded: false,
    shipmentNotes: 'Shipping available at additional cost',
    status: 'available',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    color: 'Gray',
    condition: 'Used',
  },
  {
    id: 7,
    title: 'Ford Explorer XLT 2022',
    make: 'Ford',
    model: 'Explorer',
    year: 2022,
    price: 29500,
    mileage: 28000,
    location: 'canada',
    shipmentIncluded: false,
    shipmentNotes: 'Shipping available at additional cost',
    status: 'available',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    color: 'Gray',
    condition: 'Used',
  },
  {
    id: 8,
    title: 'Explorer XLT 2022',
    make: 'Ford',
    model: 'Explorer',
    year: 2022,
    price: 29500,
    mileage: 28000,
    location: 'Ghana',
    shipmentIncluded: false,
    shipmentNotes: 'Shipping available at additional cost',
    status: 'available',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    color: 'Gray',
    condition: 'Used',
  },
  {
    id: 9,
    title: 'Toyota XLT 2022',
    make: 'Ford',
    model: 'Explorer',
    year: 2022,
    price: 29500,
    mileage: 28000,
    location: 'canada',
    shipmentIncluded: false,
    shipmentNotes: 'Shipping available at additional cost',
    status: 'available',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    color: 'Gray',
    condition: 'Used',
  },
]

export const featuredVehicles = vehicleData.filter(v => v.isFeatured)